---
name: metal-stack component release

on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@v1
    permissions:
      contents: write

  go-build:
    uses: metal-stack/actions-common/.github/workflows/go-build.yaml@v1
    permissions:
      packages: write
    secrets: inherit
    with:
      build-command: make all
